### ISSUE TITLE
Home assistant 2022.7.0 Satel error 

### ISSUE THREAD

**Issue by FranSooS** [home-assistant/home-assistant.github.io#23309]
### Feedback

Hi all,

After the update to 2022.7.0 Satel would start anymore.

I get the following error
satel_integra.satel_integra] Exception during connecting: BaseEventLoop.create_connection() got an unexpected keyword argument 'loop'.

Anyone else having this problem?

Does anyone know how I can fix this?

 Hope someone can help me.  thanks in advance

### URL

https://www.home-assistant.io/integrations/satel_integra/

### Version

2022.7.0

### Additional information

satel_integra.satel_integra] Exception during connecting: BaseEventLoop.create_connection() got an unexpected keyword argument 'loop'.

Logger: satel_integra.satel_integra
Source: /usr/local/lib/python3.10/site-packages/satel_integra/satel_integra.py:180
First occurred: 18:58:09 (1 occurrences)
Last logged: 18:58:09

Exception during connecting: BaseEventLoop.create_connection() got an unexpected keyword argument 'loop'.

**Comment by salustre** [comment]
Same here! 
I had to downgrade to Home Assistant Core 2022.6.7

I believe it has something to do with the new version of Python or related modules.  Just hope it'll be fixed soon by the author of satel integration.

**Comment by klaasnicolaas** [comment]
Hi there @FranSooS 👋

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. Please raise an issue in the Home Assistant core issue tracker instead:

https://github.com/home-assistant/core/issues

Thanks! 👍

./Klaas
