### ISSUE TITLE
after update to 2023.05 KEBA stopped working

### ISSUE THREAD

**Issue by ELFHOUSE** [home-assistant/home-assistant.github.io#27649]
### Feedback

This error originated from a custom integration.

Logger: homeassistant.config_entries
Source: custom_components/keba/__init__.py:139
Integration: Keba Charging Station
First occurred: 20:27:49 (1 occurrences)
Last logged: 20:27:49

Error setting up entry P30 for keba
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 387, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/keba/__init__.py", line 139, in async_setup_entry
    hass.config_entries.async_setup_platforms(
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ConfigEntries' object has no attribute 'async_setup_platforms'

### URL

https://www.home-assistant.io/integrations/keba/

### Version

2023.5.4

**Comment by klaasnicolaas** [comment]
Given what you're using, it's about a custom component. You are here on the wrong place, you need to be with the author of this custom component.

./Klaas
