### ISSUE TITLE
Season (customized Integration) no longer works

### ISSUE THREAD

**Issue by bearhntr** [home-assistant/home-assistant.github.io#27503]
### Feedback

https://www.home-assistant.io/integrations/season/

No longer works after upgrade to 2023.5.x

{from the logs)
**_This error originated from a custom integration.

Logger: homeassistant.config_entries
Source: custom_components/season/__init__.py:10
Integration: Season
First occurred: 17:43:55 (1 occurrences)
Last logged: 17:43:55

Error setting up entry Season for season
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 387, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/season/__init__.py", line 10, in async_setup_entry
    hass.config_entries.async_setup_platforms(entry, PLATFORMS)
AttributeError: 'ConfigEntries' object has no attribute 'async_setup_platforms'_**

![image](https://github.com/home-assistant/home-assistant.io/assets/100164602/df1b748b-4ed6-4d36-9c8b-da92de5e573b)

Home Assistant 2023.5.3
Supervisor 2023.04.1
Operating System 10.1
Frontend 20230503.3 - latest

### URL

https://www.home-assistant.io/integrations/season/

### Version

2023.5.3

### Additional information

I keep my system up to date - weekly applying updates.  I held off on the 2023.5.x updates - as I had read too many issues with them.  Then I started having issues with ZWAVE and ZIGBEE on my system - so I updated - and now not only are they not working...but now this Integration stopped too.

**Comment by bearhntr** [comment]
Is there a way to fix this?  It broke after the latest OS upgrade and when I moved to 2023.5.3.

**Comment by bearhntr** [comment]
I have DELETED this 4x now, and the last 2 times - I rebooted after the delete.  Then re-added the Integration.  It still does not work.  All I get is this same error:

**This error originated from a custom integration.

Logger: homeassistant.config_entries
Source: custom_components/season/__init__.py:10
Integration: Season
First occurred: May 30, 2023 at 18:53:55 (3 occurrences)
Last logged: 09:27:29

Error setting up entry Season for season
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 387, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/season/__init__.py", line 10, in async_setup_entry
    hass.config_entries.async_setup_platforms(entry, PLATFORMS)
AttributeError: 'ConfigEntries' object has no attribute 'async_setup_platforms'**

**Comment by klaasnicolaas** [comment]
Since it concerns a custom component, you are not at the right place here and you can better ask this question to the author of the custom component you are using.

./Klaas

**Comment by bearhntr** [comment]
> Since it concerns a custom component, you are not at the right place here and you can better ask this question to the author of the custom component you are using.
> 
> ./Klaas

This is not a CUSTOM COMPONENT.  It is found by going into ADD INTEGRATION and Searching for it.

![image](https://github.com/home-assistant/home-assistant.io/assets/100164602/2cfc1ef4-906c-440a-9e13-480f6ad3a358)

**Comment by klaasnicolaas** [comment]
You are using a custom component...

```txt
Source: custom_components/season/init.py:10
```
